#!/usr/bin/env python3
"""Emit STORYBOARD.md from board.json.

The frame book is generated rather than hand-typed for one reason: `map-shots.py`
parses it to anchor every frame to its own narration line at cut time, and on the
last film a hand-written board drifted out of that format badly enough that the
mapping was abandoned mid-assembly and replaced with an even spread. Every image
then landed near its line instead of on it, and the cut had to be rebuilt.

Row format is load-bearing. Do not restyle it:
    | **b01** | *"the line"* | 5.1 | STILL | behaviour | camera | scene |
"""
import json, re
from pathlib import Path

FILM = Path(__file__).resolve().parent
board = json.loads((FILM / 'production' / 'board.json').read_text())
RUNTIME = 405.0                      # 6:45 estimate at the measured house rate

ACTS = [
    ("ACT 1 — THE CAUSES YOU WERE HANDED", 1, 11,
     "Establish the shape of a cause before naming any of the three. The viewer "
     "should feel recognised, not lectured."),
    ("ACT 2 — THE CHEMICAL", 12, 32,
     "Dopamine is surprise, not pleasure. Wanting fell over; liking did not. Land "
     "on the viewer having named the wrong half."),
    ("ACT 3 — THE GENE", 33, 44,
     "Enter through the dopamine receptor so the two stories touch literally. Hold "
     "the Munafo caution: contested and nice to publish, NOT simply wrong."),
    ("ACT 4 — THE SAMPLE", 45, 54,
     "Who was in the room. The measurers were the outliers. Introduce THE RULER."),
    ("ACT 5 — THE TURN", 55, 66,
     "Turkheimer. Same trait, same test, two numbers, two rooms. The single fact "
     "that dissolves the other two. This is the film's centre of gravity."),
    ("ACT 6 — WHAT SURVIVED, AND THE CONFESSION", 67, 78,
     "Refuse the easy ending. Then turn the ruler on ourselves and land the title."),
]

words = [len(f['line'].split()) for f in board]
total = sum(words)
for f, w in zip(board, words):
    f['dur'] = round(RUNTIME * w / total, 1)

L = []
w = L.append
w("# STORYBOARD — Who You Measured")
w("")
w("**Generated by `make-storyboard.py` from `production/board.json`. Do not hand-edit —")
w("edit `board.py` and re-run, or the frame book and the prompts drift apart.**")
w("")
w(f"**{len(board)} frames · one per sentence · ~{int(RUNTIME//60)}:{int(RUNTIME%60):02d} "
  f"estimated narration · mean hold {RUNTIME/len(board):.2f}s**")
w("")
w("Register gate: **EXIT 0**, all six measures in band "
  "(you 35.71 · we 9.35 · syll/word 1.34 · words/sent 15.08 · ease 77.80 · FK 6.15).")
w("")
w("---")
w("")
w("## 0. The film opens COLD")
w("")
w("Frame `b01` is the first image. No title, no channel mark, no logo, no build.")
w("Narration starts in the first breath. The mark belongs to the colophon at the end.")
w("(PLAYBOOK 10.31.)")
w("")
w("## 1. What is true of every frame")
w("")
w("The world clause is in `WORLD.md` and is **locked** — 7 test images, $0.28.")
w("Two inks on off-white stock, coarse halftone, misregistration without a fixed")
w("direction, no gradients, no text of any kind.")
w("")
w("**THIS FILM HAS NO CAST.** No people, no figures, no faces, no hands, in any")
w("frame. The world test showed the character does not survive halftone plus")
w("misregistration. `board.py` refuses to emit prompts if any scene names one.")
w("")
w("## 2. The four motifs")
w("")
w("| motif | what it is | where it recurs |")
w("|---|---|---|")
w("| **THE DOT** | one measured person, always a plain disc | throughout |")
w("| **THE ARROW** | a cause | planted `b07`, paid off `b72` bent back on itself |")
w("| **THE ROOMS** | two rooms in cross-section | **the turn**, `b59` `b60` `b61` |")
w("| **THE RULER** | the instrument | `b45`, turned on itself `b75` |")
w("")
w("An object that recurs must be the SAME object, not a description rewritten each")
w("time — that is what produced books-for-sheaf on the last film (PLAYBOOK 10.38).")
w("")
w("## 3. Camera quota — enforced in `board.py`, not aspired to")
w("")
cams = {}
for f in board:
    cams[f['camera']] = cams.get(f['camera'], 0) + 1
w("| camera | count | floor |")
w("|---|---:|---:|")
FLOOR = {'XCU': 6, 'CU': 6, 'OVER': 6, 'LOW': 6, 'XWIDE': 8, 'MED': '—', 'WIDE': '—'}
for k in ['XCU', 'CU', 'MED', 'WIDE', 'XWIDE', 'OVER', 'LOW']:
    w(f"| {k} | {cams.get(k, 0)} | {FLOOR[k]} |")
w("")
w("No more than **three consecutive frames** share a camera distance. The previous")
w("film shipped six near-identical desk shots in a row and it was invisible until")
w("all four contact sheets were laid out together.")
w("")
w("## 4. Motion")
w("")
w("**STILLS ONLY.** No clips on this film, by decision. Each frame gets the")
w("deterministic push in `assemble.mjs`; nothing is bought.")
w("")
w("---")
w("")
w("## 5. The frame book")
w("")
for title, lo, hi, intent in ACTS:
    span = board[lo - 1:hi]
    secs = sum(f['dur'] for f in span)
    w(f"### {title} · {len(span)} frames · {secs:.0f}s")
    w("")
    w(f"*{intent}*")
    w("")
    w("| frame | narration | s | motion | behaviour | camera | the picture |")
    w("|---|---|---|---|---|---|---|")
    for f in span:
        line = f['line'].replace('|', '\\|')
        scene = f['scene'].replace('|', '\\|')
        w(f"| **{f['id']}** | *\"{line}\"* | {f['dur']} | STILL | {f['behaviour']} "
          f"| {f['camera']} | {scene} |")
    w("")
w("---")
w("")
w("## 6. Handoff")
w("")
w("`production/prompts.json` is generated by `board.py` and carries the locked world")
w("clause appended to every scene. Generate with:")
w("")
w("```")
w("node tools/video/generate-frames.mjs videos/who-you-measured --only b01 --publish")
w("```")
w("")
w("**One frame first.** It is the rule that would have saved $12.44 on the last film,")
w("and it also settles the open question in `WORLD.md`: whether the edit endpoint")
w("returns above 1920 when conditioned on a world plate alone. Never upscale into")
w("the canvas.")

(FILM / 'STORYBOARD.md').write_text('\n'.join(L) + '\n')

# The row format is what map-shots.py parses. Verify it here rather than discovering
# at cut time that the frame book and the cutter disagree.
text = (FILM / 'STORYBOARD.md').read_text()
rows = re.findall(r'^\|\s*\*\*(b\d\d)\*\*\s*\|\s*(.*?)\s*\|\s*([\d.]+)\s*\|\s*([^|]+)\|',
                  text, re.M)
print(f"STORYBOARD.md written — {len(board)} frames")
print(f"map-shots.py parse check: {len(rows)}/{len(board)} rows readable")
if len(rows) != len(board):
    missing = set(f['id'] for f in board) - set(r[0] for r in rows)
    print(f"  UNPARSEABLE: {' '.join(sorted(missing))}")
    raise SystemExit(1)
