/**
 * remote-script.ts — scaffold for a minimal Ableton Live Control Surface
 * (Remote Script) that exposes the Live Object Model over a TCP JSON-lines
 * socket, modelled on packages/kbot/src/integrations/KBotBridge/*.py:
 *
 *   __init__.py            create_instance(c_instance)
 *   <module>.py            ControlSurface subclass; schedule_message(1, tick) pump
 *   tcp_server.py          non-blocking socket + select server (no threads)
 *   README.md              install + protocol
 *
 * Actions: ping, tracks, lom_get, lom_set, lom_call, lom_describe, lom_children.
 * LOM paths use the Max LiveAPI grammar ("live_set tracks 0 devices 1").
 */

export interface RemoteScriptSpec {
  /** Folder / class name, e.g. "KbotSurface" (letters, digits, underscore). */
  name: string;
  /** TCP port (127.0.0.1). */
  port: number;
  /** Python module file name without .py (default: snake_case of name). */
  moduleName?: string;
}

export interface RemoteScriptScaffold {
  /** Folder name to create under "Remote Scripts". */
  folder: string;
  files: Record<string, string>;
}

function snake(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
}

export function writeRemoteScriptScaffold(spec: RemoteScriptSpec): RemoteScriptScaffold {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(spec.name)) {
    throw new Error(`remote script name must be a valid Python identifier (got "${spec.name}")`);
  }
  if (!Number.isInteger(spec.port) || spec.port < 1024 || spec.port > 65535) {
    throw new Error(`port must be an integer 1024..65535 (got ${spec.port})`);
  }
  const mod = spec.moduleName ?? snake(spec.name);
  const cls = spec.name;
  const files: Record<string, string> = {
    '__init__.py': initPy(cls, mod, spec.port),
    [`${mod}.py`]: surfacePy(cls, mod, spec.port),
    'tcp_server.py': tcpServerPy(cls, spec.port),
    'README.md': readmeMd(cls, mod, spec.port),
  };
  return { folder: cls, files };
}

function initPy(cls: string, mod: string, port: number): string {
  return `"""
${cls} - Ableton Live Remote Script generated by kbot.

Exposes the Live Object Model over TCP ${port} (127.0.0.1, newline-delimited
JSON). See README.md for the protocol.

Install: copy this folder to
  macOS:   ~/Music/Ableton/User Library/Remote Scripts/${cls}/
  Windows: %USERPROFILE%\\\\Documents\\\\Ableton\\\\User Library\\\\Remote Scripts\\\\${cls}\\\\
Activate: Live > Settings > Link, Tempo & MIDI > Control Surface = ${cls}
"""

try:
    from .${mod} import ${cls}
except ImportError:
    pass


def create_instance(c_instance):
    return ${cls}(c_instance)
`;
}

function surfacePy(cls: string, mod: string, port: number): string {
  return `"""
${mod}.py - ControlSurface for ${cls} (generated by kbot).

A schedule_message() tick pumps the TCP server once per Live timer tick
(~100 ms), so the socket is serviced from Live's main thread and every LOM
access happens where Live allows it. Nothing here spawns threads.

Actions (JSON objects, one per line, "id" is echoed back):
  {"action": "ping"}
  {"action": "tracks"}
  {"action": "lom_get",      "path": "live_set tracks 0", "prop": "name"}
  {"action": "lom_set",      "path": "live_set",          "prop": "tempo", "value": 124}
  {"action": "lom_call",     "path": "live_set",          "method": "create_midi_track", "args": [-1]}
  {"action": "lom_describe", "path": "live_set tracks 0 devices 0"}
  {"action": "lom_children", "path": "live_set"}
Replies: {"id": ..., "ok": true, ...} or {"id": ..., "ok": false, "error": "..."}.
"""

import logging
import os
import traceback

import Live
from ableton.v2.control_surface import ControlSurface

from .tcp_server import TCPServer

logger = logging.getLogger("${mod}")

LIST_CHILDREN = (
    "tracks", "return_tracks", "visible_tracks", "scenes", "cue_points", "devices",
    "clip_slots", "parameters", "chains", "return_chains", "drum_pads", "visible_drum_pads",
    "grooves", "control_surfaces", "sends", "take_lanes", "arrangement_clips",
    "available_input_routing_types", "available_output_routing_types",
    "available_input_routing_channels", "available_output_routing_channels",
)


def _jsonable(v, depth=0):
    """Reduce a LOM value to something json.dumps accepts."""
    if v is None or isinstance(v, (bool, int, float, str)):
        return v
    if isinstance(v, (list, tuple)):
        return [_jsonable(x, depth + 1) for x in v]
    name = getattr(v, "name", None)
    return {"type": type(v).__name__, "name": name if isinstance(name, str) else str(v)}


class ${cls}(ControlSurface):
    def __init__(self, c_instance):
        ControlSurface.__init__(self, c_instance)
        self._tcp_server = None
        try:
            self._start_logging()
            self._tcp_server = TCPServer(port=${port})
            self._tcp_server.start()
            self.schedule_message(1, self._tick)
            self.show_message("${cls}: listening on 127.0.0.1:${port}")
            logger.info("${cls} initialized")
        except Exception as e:
            self.show_message("${cls}: failed to start - %s" % e)
            logger.error("${cls} init failed: %s" % traceback.format_exc())

    # -- logging -----------------------------------------------------------

    def _start_logging(self):
        module_path = os.path.dirname(os.path.realpath(__file__))
        log_dir = os.path.join(module_path, "logs")
        if not os.path.exists(log_dir):
            os.mkdir(log_dir, 0o755)
        handler = logging.FileHandler(os.path.join(log_dir, "${mod}.log"))
        handler.setLevel(logging.INFO)
        handler.setFormatter(logging.Formatter("(%(asctime)s) [%(levelname)s] %(message)s"))
        logger.addHandler(handler)
        logger.setLevel(logging.INFO)
        self._log_handler = handler

    def _stop_logging(self):
        if hasattr(self, "_log_handler"):
            logger.removeHandler(self._log_handler)

    # -- tick loop ---------------------------------------------------------

    def _tick(self):
        if self._tcp_server:
            try:
                for cmd in self._tcp_server.process():
                    self._dispatch(cmd)
            except Exception:
                logger.error("${cls} tick error: %s" % traceback.format_exc())
        self.schedule_message(1, self._tick)

    # -- dispatch ----------------------------------------------------------

    def _dispatch(self, cmd):
        cmd_id = cmd.get("id", 0)
        action = cmd.get("action", "")
        handlers = {
            "ping": self._handle_ping,
            "tracks": self._handle_tracks,
            "lom_get": self._handle_lom_get,
            "lom_set": self._handle_lom_set,
            "lom_call": self._handle_lom_call,
            "lom_describe": self._handle_lom_describe,
            "lom_children": self._handle_lom_children,
        }
        handler = handlers.get(action)
        if not handler:
            self._tcp_server.send_response({"id": cmd_id, "ok": False, "error": "Unknown action: %s" % action})
            return
        try:
            result = handler(cmd)
            result["id"] = cmd_id
            self._tcp_server.send_response(result)
        except Exception as e:
            logger.error("${cls} action '%s' error: %s" % (action, traceback.format_exc()))
            self._tcp_server.send_response({"id": cmd_id, "ok": False, "error": str(e),
                                            "trace_tail": traceback.format_exc().strip().split("\\n")[-3:]})

    # -- LOM path resolution ----------------------------------------------

    def _resolve(self, path):
        """Walk a Max-LiveAPI-style path ("live_set tracks 0 devices 1") to an object."""
        tokens = [t for t in str(path or "live_set").split(" ") if t]
        if not tokens:
            return self.song()
        head = tokens.pop(0)
        if head == "live_set":
            obj = self.song()
        elif head == "live_app" or head == "app":
            obj = self.application()
        elif head == "this_device" or head == "control_surfaces":
            raise ValueError("path root '%s' is not available from a Remote Script" % head)
        else:
            raise ValueError("path must start with live_set or live_app (got '%s')" % head)
        while tokens:
            name = tokens.pop(0)
            if not hasattr(obj, name):
                raise ValueError("'%s' has no child '%s'" % (type(obj).__name__, name))
            child = getattr(obj, name)
            if tokens and tokens[0].lstrip("-").isdigit() and name in LIST_CHILDREN:
                idx = int(tokens.pop(0))
                items = list(child)
                if idx < 0 or idx >= len(items):
                    raise IndexError("%s index %d out of range (0-%d)" % (name, idx, len(items) - 1))
                obj = items[idx]
            else:
                obj = child
        return obj

    # -- handlers ----------------------------------------------------------

    def _handle_ping(self, cmd):
        return {"ok": True, "service": "${cls}", "version": "0.1.0",
                "live_version": "%d.%d.%d" % (Live.Application.get_major_version(),
                                             Live.Application.get_minor_version(),
                                             Live.Application.get_bugfix_version())}

    def _handle_tracks(self, cmd):
        out = []
        for i, t in enumerate(self.song().tracks):
            out.append({"index": i, "name": t.name, "has_midi_input": t.has_midi_input,
                        "is_foldable": t.is_foldable, "mute": t.mute, "solo": t.solo,
                        "arm": t.arm if t.can_be_armed else False,
                        "devices": [d.name for d in t.devices]})
        return {"ok": True, "tracks": out,
                "return_tracks": [t.name for t in self.song().return_tracks]}

    def _handle_lom_get(self, cmd):
        obj = self._resolve(cmd.get("path"))
        prop = cmd.get("prop")
        if not prop:
            raise ValueError("missing 'prop'")
        if not hasattr(obj, prop):
            raise ValueError("'%s' has no property '%s'" % (type(obj).__name__, prop))
        return {"ok": True, "path": cmd.get("path"), "prop": prop, "value": _jsonable(getattr(obj, prop))}

    def _handle_lom_set(self, cmd):
        obj = self._resolve(cmd.get("path"))
        prop = cmd.get("prop")
        if not prop:
            raise ValueError("missing 'prop'")
        if not hasattr(obj, prop):
            raise ValueError("'%s' has no property '%s'" % (type(obj).__name__, prop))
        setattr(obj, prop, cmd.get("value"))
        return {"ok": True, "path": cmd.get("path"), "prop": prop, "value": _jsonable(getattr(obj, prop))}

    def _handle_lom_call(self, cmd):
        obj = self._resolve(cmd.get("path"))
        method = cmd.get("method")
        if not method:
            raise ValueError("missing 'method'")
        fn = getattr(obj, method, None)
        if fn is None or not callable(fn):
            raise ValueError("'%s' has no method '%s'" % (type(obj).__name__, method))
        args = cmd.get("args") or []
        result = fn(*args)
        return {"ok": True, "path": cmd.get("path"), "method": method, "result": _jsonable(result)}

    def _handle_lom_describe(self, cmd):
        obj = self._resolve(cmd.get("path"))
        props, methods, children = [], [], []
        for name in dir(obj):
            if name.startswith("_"):
                continue
            try:
                attr = getattr(obj, name)
            except Exception:
                continue
            if callable(attr):
                methods.append(name)
            elif name in LIST_CHILDREN:
                try:
                    children.append({"name": name, "count": len(list(attr))})
                except Exception:
                    children.append({"name": name})
            else:
                props.append({"name": name, "value": _jsonable(attr)})
        return {"ok": True, "path": cmd.get("path"), "type": type(obj).__name__,
                "properties": props, "children": children, "methods": methods}

    def _handle_lom_children(self, cmd):
        obj = self._resolve(cmd.get("path"))
        counts = {}
        for name in LIST_CHILDREN:
            if hasattr(obj, name):
                try:
                    counts[name] = len(list(getattr(obj, name)))
                except Exception:
                    pass
        return {"ok": True, "path": cmd.get("path"), "type": type(obj).__name__, "counts": counts}

    # -- lifecycle ---------------------------------------------------------

    def disconnect(self):
        self.show_message("${cls}: disconnecting")
        logger.info("${cls} disconnecting")
        if self._tcp_server:
            self._tcp_server.shutdown()
        self._stop_logging()
        super(${cls}, self).disconnect()
`;
}

function tcpServerPy(cls: string, port: number): string {
  return `"""
tcp_server.py - Non-blocking TCP JSON-lines server for ${cls} (generated by kbot).

socket + select, no threads: process() is called from the ControlSurface tick
and returns any complete JSON commands that arrived since the last call.
"""

import json
import logging
import select
import socket

logger = logging.getLogger("${cls.toLowerCase()}")

LISTEN_HOST = "127.0.0.1"
LISTEN_PORT = ${port}
RECV_BUFFER = 65536


class TCPServer(object):
    def __init__(self, host=LISTEN_HOST, port=LISTEN_PORT):
        self.host = host
        self.port = port
        self._server_socket = None
        self._client_socket = None
        self._client_buffer = ""
        self._running = False

    def start(self):
        try:
            self._server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self._server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            self._server_socket.setblocking(False)
            self._server_socket.bind((self.host, self.port))
            self._server_socket.listen(1)
            self._running = True
            logger.info("${cls} TCP server listening on %s:%d" % (self.host, self.port))
        except OSError as e:
            logger.error("${cls}: could not bind %s:%d - %s" % (self.host, self.port, e))
            self._server_socket = None
            raise

    def process(self):
        commands = []
        if not self._running or not self._server_socket:
            return commands
        try:
            readable, _, _ = select.select([self._server_socket], [], [], 0)
            if readable:
                new_client, addr = self._server_socket.accept()
                new_client.setblocking(False)
                if self._client_socket:
                    try:
                        self._client_socket.close()
                    except Exception:
                        pass
                    self._client_buffer = ""
                self._client_socket = new_client
                logger.info("${cls}: client connected from %s:%d" % addr)
        except Exception:
            pass
        if self._client_socket:
            try:
                readable, _, errored = select.select([self._client_socket], [], [self._client_socket], 0)
                if errored:
                    self._disconnect_client()
                    return commands
                if readable:
                    data = self._client_socket.recv(RECV_BUFFER)
                    if not data:
                        self._disconnect_client()
                        return commands
                    self._client_buffer += data.decode("utf-8", errors="replace")
            except (ConnectionResetError, BrokenPipeError, OSError):
                self._disconnect_client()
                return commands
        while "\\n" in self._client_buffer:
            line, self._client_buffer = self._client_buffer.split("\\n", 1)
            line = line.strip()
            if not line:
                continue
            try:
                cmd = json.loads(line)
                if isinstance(cmd, dict):
                    commands.append(cmd)
            except ValueError:
                logger.warning("${cls}: malformed JSON: %s" % line[:200])
        return commands

    def send_response(self, response):
        if not self._client_socket:
            return
        try:
            self._client_socket.sendall((json.dumps(response, default=str) + "\\n").encode("utf-8"))
        except (ConnectionResetError, BrokenPipeError, OSError) as e:
            logger.warning("${cls}: send failed - %s" % e)
            self._disconnect_client()

    def _disconnect_client(self):
        if self._client_socket:
            try:
                self._client_socket.close()
            except Exception:
                pass
            self._client_socket = None
            self._client_buffer = ""
            logger.info("${cls}: client disconnected")

    def shutdown(self):
        self._running = False
        self._disconnect_client()
        if self._server_socket:
            try:
                self._server_socket.close()
            except Exception:
                pass
            self._server_socket = None
        logger.info("${cls} TCP server shut down")
`;
}

function readmeMd(cls: string, mod: string, port: number): string {
  return `# ${cls} - Ableton Live Remote Script (generated by kbot)

A minimal Control Surface that exposes the Live Object Model over a TCP
JSON-lines socket on 127.0.0.1:${port}. Same shape as kbot's KBotBridge:
\`__init__.py\` (create_instance), \`${mod}.py\` (ControlSurface with a
schedule_message tick), \`tcp_server.py\` (socket + select, no threads).

## Install

1. Copy this folder to
   - macOS: \`~/Music/Ableton/User Library/Remote Scripts/${cls}/\`
   - Windows: \`%USERPROFILE%\\Documents\\Ableton\\User Library\\Remote Scripts\\${cls}\\\`
2. Restart Live (or re-scan), then Settings > Link, Tempo & MIDI > Control Surface: ${cls}
   (Input/Output: None).
3. Live shows "${cls}: listening on 127.0.0.1:${port}" in the status bar. Logs land in \`logs/${mod}.log\`.

## Protocol

One JSON object per line; \`id\` is echoed back.

    {"id":1,"action":"ping"}
    {"id":2,"action":"tracks"}
    {"id":3,"action":"lom_get","path":"live_set tracks 0","prop":"name"}
    {"id":4,"action":"lom_set","path":"live_set","prop":"tempo","value":124}
    {"id":5,"action":"lom_call","path":"live_set","method":"create_midi_track","args":[-1]}
    {"id":6,"action":"lom_describe","path":"live_set tracks 0 devices 0"}
    {"id":7,"action":"lom_children","path":"live_set"}

Paths follow the Max LiveAPI grammar (\`live_set\`, \`live_app\`, then attribute names with list
indexes: \`tracks 0 clip_slots 2 clip\`, \`master_track mixer_device volume\`).
Every mutation is read back: \`lom_set\` replies with the value Live reports.

Test from a shell:

    printf '{"id":1,"action":"ping"}\\n' | nc 127.0.0.1 ${port}
`;
}
